<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QA1TSQG" tests="1" failures="1" timestamp="5 Jan 2020 07:03:19 GMT" time="0.012" errors="0">
  <testcase name="Testdemo" time="0.005" classname="Test1">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at Test1.Testdemo(Test1.java:7)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- Testdemo -->
</testsuite>
